spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/integratedCart_db
    driverClassName: org.postgresql.Driver
    username: integratedCart_user
    password: integratedCart_user
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  security:
    aes-secret: "ThisIsASecretKeyForAES256Encrypt" # 임시로 직접 기입 (검증용)
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
google:
  ai:
    api-key: ${GOOGLE_AI_API_KEY}
    model: gemini-pro
